version: 2
updates:
  - package-ecosystem: npm
    directories:
      - '/'
      - '/ember-liveagent'
      - '/test-app'
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
